### ISSUE TITLE
with TIME! values, out-of -bounds numerical selectors give NONE, with DATE! they give an error

### ISSUE THREAD

**Issue by meijeru** [rebol/rebol#12]
Since the introduction of `/hour /minute /second` selectors for `date!` values which do NOT correspond to numerical selectors, it is an error for numerical selectors to be outside the range `1 .. 9`.
With `time!` values, out of bound numerical selector values give simply `none`.
In an earlier issue Carl said that "`none` is the correct return value for an out-of-range ordinal selector".

BTW, why could not `/hour /minute` and `/second` correspond to, say, `/10 /11` and `/12`? 
To be noted also that `/julian == /yearday (== /8)` on date values but it does not exist on the `now` function.

Reference: http://curecode.org/rebol3/ticket.rsp?id=1375

**Comment by BrianHawley** [comment]
Why do we allow numeric selectors for time! and date! at all? Is it to support access with the ordinal functions? Reassigning ordinal functions to other names to use as accessors is a standard Rebol optimization technique...

**Comment by meijeru** [comment]
What is the relative efficiency of `d/yearday`, `eighth d`, '`pick d 8` or `d/8`?

**Comment by BrianHawley** [comment]
Hard to say what the difference would be in efficiency. It's more of a matter of preference. Nonetheless, I would prefer to use `select` instead of `pick` here. The main problem is that the numeric accessors are completely nonsensical, while named accessors actually make sense. _It would be a real usability enhancement to get rid of the numeric accessors altogether for dates and times_.

If we can do

``` rebol
select d 'yearday
```

that would be preferable to

``` rebol
pick d 8
```

because that number is basically magic.

**Comment by meijeru** [comment]
I agree the numerical selectors are not helpful because (a) they are not mnemonic and  (b) they are giving the false impression that the data/time value is stored as a block rather than as an (optimized) record. So this becomes a proposal for change. Where else than here should I put it? Also, I will put up my wish for an extra refinement to the `now` function, to yield the julian day number, _somewhere_ (preferably here on Git, unless otherwise advised).

**Comment by BrianHawley** [comment]
Put new requests as issues here. We can copy them to CureCode if need be. I've had a bit of difficulty mapping the CureCode process model to the Github development process, so using issues here might be a better approach for now.
