### ISSUE TITLE
Rename the SPLIT/INTO refinement (cc#1886)

### ISSUE THREAD

**Issue by onetom** [rebol/rebol#131]
According to http://issue.cc/r3/1886 we have a SPLIT function separate from the PARSE now, but BrianH pointed out that the /INTO refinement is not very good.

Please debate.

**Comment by earl** [comment]
Please keep the discussion of issues/bugs/wishes on CureCode for now: [CureCode issue #2051](http://issue.cc/r3/2051) was created to discuss the renaming of /INTO.
