### ISSUE TITLE
Feature Request: Make Rebol respect http_proxy and https_proxy environment variables

### ISSUE THREAD

**Issue by mydoghasworms** [rebol/rebol#224]
It would be helpful if Rebol respected the `http_proxy` and `https_proxy` environment variables for routing http(s) requests through a proxy. These environment variables are widely respected by convention for determining proxy settings.

**Comment by rebolek** [comment]
+1

**Comment by earl** [comment]
Thanks for the suggestion. I added this to CureCode as [issue #2205](http://issue.cc/r3/2205), as we still use CureCode as our primary bug database.
