### ISSUE TITLE
TRANSCODE /part option

### ISSUE THREAD

**Issue by BrianHawley** [rebol/rebol#23]
Embedded scripts need to decode the binary source from a start position only to a particular end position, and shouldn't go any further. This kind of thing happens with the length-specified embedded scripts that `sys/load-header` enables, but it could also happen with something like RSP template dialects. When we needed to support such limits in `sys/load-header` for checksums and decompression, we added a `/part` option to `checksum` and `decompress`. We need a similar `/part` option for `transcode`.

For this example data:

``` rebol
>> s: to-binary {rebol [] print "Hello!" stuff after the script}
== #{
7265626F6C205B5D207072696E74202248656C6C6F2122207374756666206166
7465722074686520736372697074
}
```

Code required now if you use `to block!`:

``` rebol
>> d: to block! copy/part s 23  ; note the copy overhead here
== [rebol [] print "Hello!"]
>> e: skip s 23
== #{2073747566662061667465722074686520736372697074}
```

Code required now if you use `transcode`:

``` rebol
>> d: head clear back tail transcode copy/part s 23  ; still copy overhead
== [rebol [] print "Hello!"]
>> e: skip s 23
== #{2073747566662061667465722074686520736372697074}
```

Yes, the `head clear back tail` stuff is dumb, but that will be discussed in another issue.

Code required now if you use `transcode/part`:

``` rebol
>> d: transcode/part s 23  ; no copy overhead here
== [rebol [] print "Hello!" #{2073747566662061667465722074686520736372697074}]
>> e: last d
== #{2073747566662061667465722074686520736372697074}
>> head clear back tail d
== [rebol [] print "Hello!"]
```

Still has the stupid API `clear back tail` problem (another issue), but at least it doesn't have the copy overhead anymore.

**Comment by carls** [comment]
Brian, is this in curecode yet?

**Comment by BrianHawley** [comment]
Yes, http://issue.cc/r3/1915 - you can remove it.
