### ISSUE TITLE
[OS X] The builtin editor freezes permanently on exceptions.

### ISSUE THREAD

**Issue by carlsmith** [rebol/rebol#243]
I was following [this tutorial](http://www.rebol.com/docs/quick-start2.html) and it suggested introducing a bug to see the error message. I tried it and it froze every Rebol window on my system. I tried it a number of times, and everything works perfectly until you hit <kbd>Ctrl-E</kbd> in the editor with any error in the source. It just freezes [little spinning umbrella thingy forever.]

OS X 10.10.2
Model Name: MacBook Air
  Processor Name:   Intel Core i5
  Processor Speed:  1.3 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache (per Core):  256 KB
  L3 Cache: 3 MB
  Memory:   4 GB
  Boot ROM Version: MBA61.0099.B18
  SMC Version (system): 2.13f15

**Comment by earl** [comment]
Hi Carl! Thanks a lot for taking the time to report on this bug; sorry for any inconvenience it caused. 

Unfortunately, this here is an issue tracker for Rebol 3, whereas the tutorial you are working through is for Rebol 2. The proper bug tracker for Rebol 2 is ["RAMBO"](http://www.rebol.net/cgi-bin/rambo.r), so if you'd be so kind and report the bug there.

**Comment by carlsmith** [comment]
Will do, and thank you for fixing the account so quickly.
