### ISSUE TITLE
strange behaviour in windows 8

### ISSUE THREAD

**Issue by angerangel** [rebol/rebol#244]
From: http://rebol.informe.com/forum/rebol-2-f8/strange-behaviour-in-windows-8-t132.html

It seems rebol has a bug that appears in windows 8 (or maybe it is windows 8 which has a bug)

when you create a file in root partion of disk C it becomes unvisible in windows explorer, windows command line and whatever windows program accesing c:\ folder, that file is in another universe for windows point of view.

```
>> save %/c/a.txt "hello universe!"

c:\> dir
```

(no clue about a.txt)

But if you do a dir list in rebol view console, it is there! and you can read it, load it and even delete it

```
>> ls %/c/

$Recycle.Bin/ a.txt Users/ Windows/
```

The effect of this weird bug is you cannot open any file created from rebol view 2.7 with any windows program, files created inside rebol are only visible to rebol. But this only happen with files created in root folder, if you create files in any other folder all seems to be ok.

```
>> save %/c/aeat/b.txt "hello universe"
>> ls %/c/aeat
b.txt
```

any idea of this weird windowness?

**Comment by earl** [comment]
This question has also been posted to StackOverflow Q&A, and since been answered there:

http://stackoverflow.com/questions/29595477/rebol-2-has-a-bug-creating-files-in-windows-8
