### ISSUE TITLE
Likely crash in do_callback

### ISSUE THREAD

**Issue by kjk** [rebol/rebol#25]
In f-extension.c:

``` c
*/  REBNATIVE(do_callback)
/*
**      object word arg1 arg2
**
***********************************************************************/
{
    RXICBI *cbi;
    REBVAL *event = D_ARG(1);
    REBCNT n;

    if (VAL_EVENT_TYPE(event) == EVT_CALLBACK) {
        if (cbi = VAL_EVENT_SER(event)) {
            n = Do_Callback(cbi->obj, cbi->word, cbi->args, &(cbi->result));
        }
    }

    SET_FLAG(cbi->flags, RXC_DONE);
```

If event is not EVT_CALLBACK, cbi will not be initialized and the code will likely crash trying to access it.
I guess it's possible to write a test script to exercise this codepath, but I'm not there yet.

**Comment by carls** [comment]
And... all the code that follows would be invalid. Looking into it...

**Comment by carls** [comment]
Fixed. Picked a no-op result vs forcing a trap.
