### ISSUE TITLE
Is it possible to build REBOL without using the prebuilt binary?

### ISSUE THREAD

**Issue by pkillnine** [rebol/rebol#252]

**Comment by pkillnine** [comment]
Nevermind, I only saw the `.r` files and didn't notice that it builds Rebol using `c` files.

**Comment by pkillnine** [comment]
Actually scratch that, the instructions say parts of it are built using Rebol. So is there a way to build it completely without any parts of it being built using a prebuilt Rebol binary?

**Comment by iceflow19** [comment]
I recommend you dont start issues on this repo, but on the Ren/C project where the majority of new work on Rebol3 is occurring.


 https://github.com/metaeducation/ren-c

**Comment by pkillnine** [comment]
ok, thanks
