### ISSUE TITLE
Incorrect use of APPEND_BYTES

### ISSUE THREAD

**Issue by kjk** [rebol/rebol#26]
In d-crash.c, APPEND_BYTES is strncat and used as: APPEND_BYTES(buf, s, sizeof(buf)).

This will over-write the buf if s is longer than buf and buf is not empty. The last argument of strncat is max number of characters to append to buf, so if buf is not empty, passing sizeof(buf) allows for overwrite.

A quick hack would be to define APPEND_BYTES(dst, src, len) as strncat(dst, src, len - strlen(dst) - 1 > 0 ? len - strlen(dst) - 1 : 0 )

**Comment by carls** [comment]
Good catch.

**Comment by carls** [comment]
fixed
