### ISSUE TITLE
`make all` fails with "strip: 'libr3.lib': No such file"

### ISSUE THREAD

**Issue by digulla** [rebol/rebol#43]
When running "make all", it fails at the end with

```
make[1]: Entering directory `/home/adigulla/packages/r3/make'
gcc -o host objs/host-main.o objs/host-args.o objs/host-device.o objs/host-stdio.o objs/dev-net.o objs/dev-dns.o objs/host-lib.o objs/host-readline.o objs/dev-stdio.o objs/dev-event.o objs/dev-file.o  libr3.so -lc -lm  -ldl -m32
strip libr3.lib
strip: 'libr3.lib': No such file
```

This is probably just because it uses the wrong file name.

I'm on Linux x86/64 with 32bit compiler + 32bit dependencies installed.

**Comment by digulla** [comment]
The error has been fixed in make-make.r but the makefile that git clones for you hasn't been recreated.

**Comment by carls** [comment]
We'll get that updated, thanks.
