### ISSUE TITLE
Please read the latest R3 Chat messages ;-)

### ISSUE THREAD

**Issue by ladislav** [rebol/rebol#62]

**Comment by angerangel** [comment]
```
>> chat
Fetching chat...
Script: "RebDev Command Line Interface" Version: 0.4.27 Date: 9-Sep-2010
0 message records

Alerts:
--- Note: no messages

Top headings:
--- Note: no messages

Hint: n = new messages, who = users online, ? = help, ?? = list commands.
--- Note: Not logged in. Use LOGIN or NEW-USER.

*off-line* guest:(no topic)>>
```

_??_

**Comment by ladislav** [comment]
you need to LOGIN or define yourself as NEW-USER as indicated

**Comment by angerangel** [comment]
```
*off-line* guest:(no topic)>> new-user
Username? MaxV
Username: "maxv"
Full name? Massimiliano Vessi
An email address is needed for account validation.
Email address? maxint@tiscali.it
*** RebDev Error:  (email-failed)
```

**Comment by angerangel** [comment]
Please, could you public it here?

**Comment by pierrechtux** [comment]
Hello,

I just tried, no success:

> > chat
> > Fetching chat...
> > Script: "RebDev Command Line Interface" Version: 0.4.27 Date: 9-Sep-2010
> > 0 message records

Alerts:
--- Note: no messages

Top headings:
--- Note: no messages

Hint: n = new messages, who = users online, ? = help, ?? = list commands.
--- Note: Not logged in. Use LOGIN or NEW-USER.

_off-line_ guest:(no topic)>> NEW-USER
Username? pierre
Username: "pierre"
Full name? Pierre Chevalier
An email address is needed for account validation.
Email address? pierrechevaliergeol@free.fr
**\* RebDev Error:  (email-failed)

_off-line_ guest:(no topic)>>

Maybe the server is down?

À+
Pierre

Le 10/01/2013 20:14, Ladislav Mecir claviota:

**Comment by earl** [comment]
The server is up, but registration for new users is not working, currently. But you can use the [RebDev Mobile](http://www.rebol.net/cgi-bin/rebdev-web.r) interface to see what's going on, esp the [new messages view](http://www.rebol.net/cgi-bin/rebdev-web.r?new=20).

**Comment by ladislav** [comment]
"but registration for new users is not working, currently" - strange, I saw a new user being registered recently

**Comment by earl** [comment]
True, seems someone managed to register today. Well, then maybe it's just the email validation logic that prohibits many users from registering, at the moment.

**Comment by angerangel** [comment]
In the end, is there something important? I didn't find anything. May you post it here, please?

**Comment by ladislav** [comment]
I meant this message, e.g.:

#8075: post from cyphre 6d ago:
Hello Carl! Sending this message from Android phone :).

**Comment by angerangel** [comment]
Rebol works also on my android devices!!!!

**Comment by carls** [comment]
Android! That's excellent. What changes need to be posted here, if any? Can someone describe if the build process is any different for Android, or is it basically the same?
