### ISSUE TITLE
SELECT/SKIP always yields one value, was not so in R2

### ISSUE THREAD

**Issue by meijeru** [rebol/rebol#8]
In REBOL 2, `select/skip` with `size n>1` yielded a block result of length `n-1`. In other words, it yielded the rest of the record. Not so in REBOL 3. Is this intentional?
Example code

```
>> s: [a 1 b 2 c 3]
>> select/skip s 'c 2
== 3 ; was [3] in REBOL 2
```

Ref: http://curecode.org/rebol3/ticket.rsp?id=730

**Comment by BrianHawley** [comment]
It is really inconvenient if so. This makes the `/skip` value inconsistent, which will require special-case code when doing generic record-oriented functions. The main advantage would be to have `/skip` 2 act more like objects and maps, but that kind of defeats the purpose of having different datatypes.

**Comment by meijeru** [comment]
I am not sure what you prefer now, the R2 semantics or the current R3 one.

**Comment by BrianHawley** [comment]
I prefer the R2 semantics in this case. It makes `select/skip` feel more record-oriented, which is the whole advantage of storing your data in fixed-length records in blocks in the first place.

**Comment by meijeru** [comment]
I could not agree more. So this becomes a proposal for change. Is there another place to put such a proposal than in this comment to an issue on Git?

**Comment by BrianHawley** [comment]
We haven't switched away from using CureCode for this kind of thing yet, and this was already reported there. Someone needs to migrate the CC tickets to issues here en-mass, at least the open ones. Also, you might want to use the issue.cc links when referring to the CureCode tickets, unless your purpose is to advertise CureCode and redirect people away from the Github issue system. I'll be monitoring both, in case Github-haters want to post things to CureCode instead.

This issue system here integrates with the Github process flow better than CC does, or even better than DevBase 3 integrated with CC. However, one feature that we really took advantage of in CC is apparently missing: the ability of the project admin to edit the original ticket (or in this case, issue). We used that to adjust the phrasing of the ticket to better reflect the real problem. With these Github issues, I can go back and edit my comments, but not the original question unless I was the one who asked it. At least as far as I know.

Doing the reports here seems to be the best plan for now.
