### ISSUE TITLE
R3 chat isn't working at present

### ISSUE THREAD

**Issue by ladislav** [rebol/rebol#95]

**Comment by carls** [comment]
Ok, I'll check on that.

**Comment by carls** [comment]
Looks like the server ran out of memory. Got to love the cloud. Anyway, rebooted it. Let me know if it comes back up or if there's any other problems with it. Thanks.

**Comment by pierrechtux** [comment]
Still, it is impossible for me to log in rebol 3 chat:
  # pierre@autan: ~$        < 2013_03_04__20_07_31 >
r3

---

---

*\*  REBOL 3.0 [Alpha Test]                                              **

---

*\*    Copyright: 2012 REBOL Technologies                                **
*\*               All rights reserved.                                   **
*\*    Website:   www.REBOL.com                                          **

---

*\*    Version:   2.101.0.4.4                                            **
*\*    Platform:  Linux libc6-2-11-x86                                   **
*\*    Build:     13-Dec-2012/20:01:22                                   **
*\*    Warning:   For testing purposes only. Use at your own risk.       **

---

*\*    Language:  none                                                   **
*\*    Locale:    none                                                   **
*\*    Home:      ./                                                     **

---

---

SECURE is disabled

Important notes:
- Sandbox and security are not available.
- Direct access to TCP HTTP required (no proxies).
- Default web browser must be available.

Special functions:

  Chat - open DevBase developer forum/BBS
  Docs - open DocBase document wiki (web)
  Bugs - open CureCode bug database (web)
  Demo - run demo launcher (from rebol.com)
  Help - show built-in help information
  Upgrade - check for newer releases
  Changes - what's new about this version (web)

> > chat
> > Fetching chat...
> > Script: "RebDev Command Line Interface" Version: 0.4.27 Date: 9-Sep-2010
> > 0 message records

Alerts:
--- Note: no messages

Top headings:
--- Note: no messages

Hint: n = new messages, who = users online, ? = help, ?? = list commands.
--- Note: Not logged in. Use LOGIN or NEW-USER.

_off-line_ guest:(no topic)>> NEW-USER 
Username? pierrech
Username: "pierrech"
Full name? Pierre Chevalier
An email address is needed for account validation.
Email address? pi....@free.fr           <= this was my _real_, _valid_ email address
**\* RebDev Error:  (email-failed)

**Comment by ladislav** [comment]
Pierre, you should create a new issue, preferably. This one is closed.
